/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface StaxVaultInterface extends Interface {
    getFunction(nameOrSignature: "BPS_DENOMINATOR" | "DEAD_ADDRESS" | "FEE_BPS" | "FEE_BURN_SHARE_BPS" | "FEE_REWARDS_SHARE_BPS" | "FEE_TREASURY_SHARE_BPS" | "MAX_SLIPPAGE_BPS" | "MIN_INITIAL_VALUE_USD" | "MIN_TOKENS_IN" | "MIN_TOKENS_OUT" | "SEQUENCER_GRACE_PERIOD" | "USDG_STALENESS_CONFIRMED_REFERENCE" | "VIRTUAL_SHARES" | "allowedHooks" | "basketTickerHoldings" | "baskets" | "claimRewardsPool" | "claimTreasuryFees" | "createBasket" | "executeBuyBurn" | "getBasketComposition" | "getBasketNavUsd" | "mint" | "owner" | "pendingBuyBurn" | "pendingRewardsPool" | "pendingTreasuryFees" | "permit2" | "priceFeeds" | "redeem" | "renounceOwnership" | "rewardsPool" | "sequencerUptimeFeed" | "setCaps" | "setHookAllowed" | "setMintPaused" | "setPriceFeed" | "setStaxSwapPool" | "setStaxToken" | "setTickerPool" | "setTickerPoolV3" | "staxSwapPool" | "staxToken" | "tickerIsV3" | "tickerPools" | "tickerPoolsV3" | "transferOwnership" | "treasury" | "universalRouter" | "updatePriceFeed" | "updateTickerPool" | "updateTickerPoolV3" | "usdg" | "usdgDecimals" | "usdgUsdFeed" | "usdgUsdMaxStaleness"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BasketCreated" | "BuyBurnExecuted" | "CapsSet" | "FeeAccrued" | "FeeSplit" | "HookAllowlistUpdated" | "MintPausedSet" | "Minted" | "OwnershipTransferred" | "PriceFeedSet" | "Redeemed" | "RewardsPoolClaimed" | "StaxSwapPoolSet" | "StaxTokenSet" | "TickerPoolSet" | "TickerPoolV3Set" | "TreasuryFeesClaimed"): EventFragment;

    encodeFunctionData(functionFragment: 'BPS_DENOMINATOR', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEAD_ADDRESS', values?: undefined): string;
encodeFunctionData(functionFragment: 'FEE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'FEE_BURN_SHARE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'FEE_REWARDS_SHARE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'FEE_TREASURY_SHARE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_SLIPPAGE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'MIN_INITIAL_VALUE_USD', values?: undefined): string;
encodeFunctionData(functionFragment: 'MIN_TOKENS_IN', values?: undefined): string;
encodeFunctionData(functionFragment: 'MIN_TOKENS_OUT', values?: undefined): string;
encodeFunctionData(functionFragment: 'SEQUENCER_GRACE_PERIOD', values?: undefined): string;
encodeFunctionData(functionFragment: 'USDG_STALENESS_CONFIRMED_REFERENCE', values?: undefined): string;
encodeFunctionData(functionFragment: 'VIRTUAL_SHARES', values?: undefined): string;
encodeFunctionData(functionFragment: 'allowedHooks', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'basketTickerHoldings', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'baskets', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'claimRewardsPool', values?: undefined): string;
encodeFunctionData(functionFragment: 'claimTreasuryFees', values?: undefined): string;
encodeFunctionData(functionFragment: 'createBasket', values: [BigNumberish, string, string, AddressLike[], BigNumberish[], BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'executeBuyBurn', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getBasketComposition', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getBasketNavUsd', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'mint', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingBuyBurn', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingRewardsPool', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingTreasuryFees', values?: undefined): string;
encodeFunctionData(functionFragment: 'permit2', values?: undefined): string;
encodeFunctionData(functionFragment: 'priceFeeds', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'redeem', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'rewardsPool', values?: undefined): string;
encodeFunctionData(functionFragment: 'sequencerUptimeFeed', values?: undefined): string;
encodeFunctionData(functionFragment: 'setCaps', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setHookAllowed', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setMintPaused', values: [BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'setPriceFeed', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setStaxSwapPool', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'setStaxToken', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setTickerPool', values: [AddressLike, AddressLike, AddressLike, BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'setTickerPoolV3', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'staxSwapPool', values?: undefined): string;
encodeFunctionData(functionFragment: 'staxToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'tickerIsV3', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'tickerPools', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'tickerPoolsV3', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'treasury', values?: undefined): string;
encodeFunctionData(functionFragment: 'universalRouter', values?: undefined): string;
encodeFunctionData(functionFragment: 'updatePriceFeed', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'updateTickerPool', values: [AddressLike, AddressLike, AddressLike, BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'updateTickerPoolV3', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'usdg', values?: undefined): string;
encodeFunctionData(functionFragment: 'usdgDecimals', values?: undefined): string;
encodeFunctionData(functionFragment: 'usdgUsdFeed', values?: undefined): string;
encodeFunctionData(functionFragment: 'usdgUsdMaxStaleness', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'BPS_DENOMINATOR', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEAD_ADDRESS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'FEE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'FEE_BURN_SHARE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'FEE_REWARDS_SHARE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'FEE_TREASURY_SHARE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_SLIPPAGE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MIN_INITIAL_VALUE_USD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MIN_TOKENS_IN', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MIN_TOKENS_OUT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SEQUENCER_GRACE_PERIOD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'USDG_STALENESS_CONFIRMED_REFERENCE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'VIRTUAL_SHARES', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allowedHooks', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'basketTickerHoldings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'baskets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimRewardsPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimTreasuryFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createBasket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeBuyBurn', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBasketComposition', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBasketNavUsd', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingBuyBurn', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingRewardsPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingTreasuryFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'permit2', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'priceFeeds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'redeem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewardsPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sequencerUptimeFeed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setCaps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setHookAllowed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMintPaused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPriceFeed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setStaxSwapPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setStaxToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTickerPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTickerPoolV3', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'staxSwapPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'staxToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tickerIsV3', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tickerPools', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tickerPoolsV3', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'universalRouter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePriceFeed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateTickerPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateTickerPoolV3', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdg', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdgDecimals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdgUsdFeed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdgUsdMaxStaleness', data: BytesLike): Result;
  }

  
    export namespace BasketCreatedEvent {
      export type InputTuple = [basketId: BigNumberish, token: AddressLike, name: string];
      export type OutputTuple = [basketId: bigint, token: string, name: string];
      export interface OutputObject {basketId: bigint, token: string, name: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BuyBurnExecutedEvent {
      export type InputTuple = [usdgSpent: BigNumberish, staxBurned: BigNumberish];
      export type OutputTuple = [usdgSpent: bigint, staxBurned: bigint];
      export interface OutputObject {usdgSpent: bigint, staxBurned: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CapsSetEvent {
      export type InputTuple = [basketId: BigNumberish, depositCapUsd: BigNumberish, maxMintUsd: BigNumberish];
      export type OutputTuple = [basketId: bigint, depositCapUsd: bigint, maxMintUsd: bigint];
      export interface OutputObject {basketId: bigint, depositCapUsd: bigint, maxMintUsd: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeeAccruedEvent {
      export type InputTuple = [basketId: BigNumberish, usdgAmount: BigNumberish];
      export type OutputTuple = [basketId: bigint, usdgAmount: bigint];
      export interface OutputObject {basketId: bigint, usdgAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeeSplitEvent {
      export type InputTuple = [toBurn: BigNumberish, toRewardsPool: BigNumberish, toTreasury: BigNumberish];
      export type OutputTuple = [toBurn: bigint, toRewardsPool: bigint, toTreasury: bigint];
      export interface OutputObject {toBurn: bigint, toRewardsPool: bigint, toTreasury: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace HookAllowlistUpdatedEvent {
      export type InputTuple = [hook: AddressLike, allowed: boolean];
      export type OutputTuple = [hook: string, allowed: boolean];
      export interface OutputObject {hook: string, allowed: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MintPausedSetEvent {
      export type InputTuple = [basketId: BigNumberish, paused: boolean];
      export type OutputTuple = [basketId: bigint, paused: boolean];
      export interface OutputObject {basketId: bigint, paused: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MintedEvent {
      export type InputTuple = [basketId: BigNumberish, user: AddressLike, usdgIn: BigNumberish, valueReceivedUsd: BigNumberish, tokensOut: BigNumberish];
      export type OutputTuple = [basketId: bigint, user: string, usdgIn: bigint, valueReceivedUsd: bigint, tokensOut: bigint];
      export interface OutputObject {basketId: bigint, user: string, usdgIn: bigint, valueReceivedUsd: bigint, tokensOut: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PriceFeedSetEvent {
      export type InputTuple = [ticker: AddressLike, feed: AddressLike, maxStaleness: BigNumberish];
      export type OutputTuple = [ticker: string, feed: string, maxStaleness: bigint];
      export interface OutputObject {ticker: string, feed: string, maxStaleness: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RedeemedEvent {
      export type InputTuple = [basketId: BigNumberish, user: AddressLike, tokensIn: BigNumberish, usdgOut: BigNumberish, valueReturnedUsd: BigNumberish];
      export type OutputTuple = [basketId: bigint, user: string, tokensIn: bigint, usdgOut: bigint, valueReturnedUsd: bigint];
      export interface OutputObject {basketId: bigint, user: string, tokensIn: bigint, usdgOut: bigint, valueReturnedUsd: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RewardsPoolClaimedEvent {
      export type InputTuple = [amount: BigNumberish];
      export type OutputTuple = [amount: bigint];
      export interface OutputObject {amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StaxSwapPoolSetEvent {
      export type InputTuple = [currency0: AddressLike, currency1: AddressLike, fee: BigNumberish, tickSpacing: BigNumberish, hooks: AddressLike];
      export type OutputTuple = [currency0: string, currency1: string, fee: bigint, tickSpacing: bigint, hooks: string];
      export interface OutputObject {currency0: string, currency1: string, fee: bigint, tickSpacing: bigint, hooks: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StaxTokenSetEvent {
      export type InputTuple = [staxToken: AddressLike];
      export type OutputTuple = [staxToken: string];
      export interface OutputObject {staxToken: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TickerPoolSetEvent {
      export type InputTuple = [ticker: AddressLike, currency0: AddressLike, currency1: AddressLike, fee: BigNumberish, tickSpacing: BigNumberish, hooks: AddressLike];
      export type OutputTuple = [ticker: string, currency0: string, currency1: string, fee: bigint, tickSpacing: bigint, hooks: string];
      export interface OutputObject {ticker: string, currency0: string, currency1: string, fee: bigint, tickSpacing: bigint, hooks: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TickerPoolV3SetEvent {
      export type InputTuple = [ticker: AddressLike, fee: BigNumberish];
      export type OutputTuple = [ticker: string, fee: bigint];
      export interface OutputObject {ticker: string, fee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TreasuryFeesClaimedEvent {
      export type InputTuple = [amount: BigNumberish];
      export type OutputTuple = [amount: bigint];
      export interface OutputObject {amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface StaxVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): StaxVault;
    waitForDeployment(): Promise<this>;

    interface: StaxVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BPS_DENOMINATOR: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    DEAD_ADDRESS: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    FEE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    FEE_BURN_SHARE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    FEE_REWARDS_SHARE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    FEE_TREASURY_SHARE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_SLIPPAGE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MIN_INITIAL_VALUE_USD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MIN_TOKENS_IN: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MIN_TOKENS_OUT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    SEQUENCER_GRACE_PERIOD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    USDG_STALENESS_CONFIRMED_REFERENCE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    VIRTUAL_SHARES: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    allowedHooks: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    basketTickerHoldings: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    baskets: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, boolean, boolean] & {name: string, token: string, depositCapUsd: bigint, maxMintUsd: bigint, mintPaused: boolean, exists: boolean }],
      'view'
    >
    

    
    claimRewardsPool: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    claimTreasuryFees: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    createBasket: TypedContractMethod<
      [basketId: BigNumberish, name: string, symbol: string, tickers: AddressLike[], weights: BigNumberish[], depositCapUsd: BigNumberish, maxMintUsd: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    executeBuyBurn: TypedContractMethod<
      [minStaxOut: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getBasketComposition: TypedContractMethod<
      [basketId: BigNumberish, ],
      [[string[], bigint[]] & {tickers: string[], weights: bigint[] }],
      'view'
    >
    

    
    getBasketNavUsd: TypedContractMethod<
      [basketId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    mint: TypedContractMethod<
      [basketId: BigNumberish, usdgAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pendingBuyBurn: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    pendingRewardsPool: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    pendingTreasuryFees: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    permit2: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    priceFeeds: TypedContractMethod<
      [arg0: AddressLike, ],
      [[string, bigint] & {feed: string, maxStaleness: bigint }],
      'view'
    >
    

    
    redeem: TypedContractMethod<
      [basketId: BigNumberish, tokenAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    rewardsPool: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    sequencerUptimeFeed: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setCaps: TypedContractMethod<
      [basketId: BigNumberish, depositCapUsd: BigNumberish, maxMintUsd: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setHookAllowed: TypedContractMethod<
      [hook: AddressLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setMintPaused: TypedContractMethod<
      [basketId: BigNumberish, paused: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setPriceFeed: TypedContractMethod<
      [ticker: AddressLike, feed: AddressLike, maxStaleness: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setStaxSwapPool: TypedContractMethod<
      [currency0: AddressLike, currency1: AddressLike, fee: BigNumberish, tickSpacing: BigNumberish, hooks: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setStaxToken: TypedContractMethod<
      [_staxToken: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setTickerPool: TypedContractMethod<
      [ticker: AddressLike, currency0: AddressLike, currency1: AddressLike, fee: BigNumberish, tickSpacing: BigNumberish, hooks: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setTickerPoolV3: TypedContractMethod<
      [ticker: AddressLike, fee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    staxSwapPool: TypedContractMethod<
      [],
      [[string, string, bigint, bigint, string] & {currency0: string, currency1: string, fee: bigint, tickSpacing: bigint, hooks: string }],
      'view'
    >
    

    
    staxToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    tickerIsV3: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    tickerPools: TypedContractMethod<
      [arg0: AddressLike, ],
      [[string, string, bigint, bigint, string] & {currency0: string, currency1: string, fee: bigint, tickSpacing: bigint, hooks: string }],
      'view'
    >
    

    
    tickerPoolsV3: TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, boolean] & {fee: bigint, exists: boolean }],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    treasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    universalRouter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    updatePriceFeed: TypedContractMethod<
      [ticker: AddressLike, feed: AddressLike, maxStaleness: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updateTickerPool: TypedContractMethod<
      [ticker: AddressLike, currency0: AddressLike, currency1: AddressLike, fee: BigNumberish, tickSpacing: BigNumberish, hooks: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateTickerPoolV3: TypedContractMethod<
      [ticker: AddressLike, fee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    usdg: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    usdgDecimals: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    usdgUsdFeed: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    usdgUsdMaxStaleness: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BPS_DENOMINATOR'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'DEAD_ADDRESS'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'FEE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'FEE_BURN_SHARE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'FEE_REWARDS_SHARE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'FEE_TREASURY_SHARE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_SLIPPAGE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MIN_INITIAL_VALUE_USD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MIN_TOKENS_IN'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MIN_TOKENS_OUT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'SEQUENCER_GRACE_PERIOD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'USDG_STALENESS_CONFIRMED_REFERENCE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'VIRTUAL_SHARES'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'allowedHooks'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'basketTickerHoldings'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'baskets'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, boolean, boolean] & {name: string, token: string, depositCapUsd: bigint, maxMintUsd: bigint, mintPaused: boolean, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'claimRewardsPool'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimTreasuryFees'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createBasket'): TypedContractMethod<
      [basketId: BigNumberish, name: string, symbol: string, tickers: AddressLike[], weights: BigNumberish[], depositCapUsd: BigNumberish, maxMintUsd: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'executeBuyBurn'): TypedContractMethod<
      [minStaxOut: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getBasketComposition'): TypedContractMethod<
      [basketId: BigNumberish, ],
      [[string[], bigint[]] & {tickers: string[], weights: bigint[] }],
      'view'
    >;
getFunction(nameOrSignature: 'getBasketNavUsd'): TypedContractMethod<
      [basketId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'mint'): TypedContractMethod<
      [basketId: BigNumberish, usdgAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pendingBuyBurn'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'pendingRewardsPool'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'pendingTreasuryFees'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'permit2'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'priceFeeds'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[string, bigint] & {feed: string, maxStaleness: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'redeem'): TypedContractMethod<
      [basketId: BigNumberish, tokenAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rewardsPool'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'sequencerUptimeFeed'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setCaps'): TypedContractMethod<
      [basketId: BigNumberish, depositCapUsd: BigNumberish, maxMintUsd: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setHookAllowed'): TypedContractMethod<
      [hook: AddressLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMintPaused'): TypedContractMethod<
      [basketId: BigNumberish, paused: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPriceFeed'): TypedContractMethod<
      [ticker: AddressLike, feed: AddressLike, maxStaleness: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setStaxSwapPool'): TypedContractMethod<
      [currency0: AddressLike, currency1: AddressLike, fee: BigNumberish, tickSpacing: BigNumberish, hooks: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setStaxToken'): TypedContractMethod<
      [_staxToken: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTickerPool'): TypedContractMethod<
      [ticker: AddressLike, currency0: AddressLike, currency1: AddressLike, fee: BigNumberish, tickSpacing: BigNumberish, hooks: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTickerPoolV3'): TypedContractMethod<
      [ticker: AddressLike, fee: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'staxSwapPool'): TypedContractMethod<
      [],
      [[string, string, bigint, bigint, string] & {currency0: string, currency1: string, fee: bigint, tickSpacing: bigint, hooks: string }],
      'view'
    >;
getFunction(nameOrSignature: 'staxToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'tickerIsV3'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'tickerPools'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[string, string, bigint, bigint, string] & {currency0: string, currency1: string, fee: bigint, tickSpacing: bigint, hooks: string }],
      'view'
    >;
getFunction(nameOrSignature: 'tickerPoolsV3'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, boolean] & {fee: bigint, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'treasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'universalRouter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'updatePriceFeed'): TypedContractMethod<
      [ticker: AddressLike, feed: AddressLike, maxStaleness: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateTickerPool'): TypedContractMethod<
      [ticker: AddressLike, currency0: AddressLike, currency1: AddressLike, fee: BigNumberish, tickSpacing: BigNumberish, hooks: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateTickerPoolV3'): TypedContractMethod<
      [ticker: AddressLike, fee: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usdg'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'usdgDecimals'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'usdgUsdFeed'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'usdgUsdMaxStaleness'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'BasketCreated'): TypedContractEvent<BasketCreatedEvent.InputTuple, BasketCreatedEvent.OutputTuple, BasketCreatedEvent.OutputObject>;
getEvent(key: 'BuyBurnExecuted'): TypedContractEvent<BuyBurnExecutedEvent.InputTuple, BuyBurnExecutedEvent.OutputTuple, BuyBurnExecutedEvent.OutputObject>;
getEvent(key: 'CapsSet'): TypedContractEvent<CapsSetEvent.InputTuple, CapsSetEvent.OutputTuple, CapsSetEvent.OutputObject>;
getEvent(key: 'FeeAccrued'): TypedContractEvent<FeeAccruedEvent.InputTuple, FeeAccruedEvent.OutputTuple, FeeAccruedEvent.OutputObject>;
getEvent(key: 'FeeSplit'): TypedContractEvent<FeeSplitEvent.InputTuple, FeeSplitEvent.OutputTuple, FeeSplitEvent.OutputObject>;
getEvent(key: 'HookAllowlistUpdated'): TypedContractEvent<HookAllowlistUpdatedEvent.InputTuple, HookAllowlistUpdatedEvent.OutputTuple, HookAllowlistUpdatedEvent.OutputObject>;
getEvent(key: 'MintPausedSet'): TypedContractEvent<MintPausedSetEvent.InputTuple, MintPausedSetEvent.OutputTuple, MintPausedSetEvent.OutputObject>;
getEvent(key: 'Minted'): TypedContractEvent<MintedEvent.InputTuple, MintedEvent.OutputTuple, MintedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PriceFeedSet'): TypedContractEvent<PriceFeedSetEvent.InputTuple, PriceFeedSetEvent.OutputTuple, PriceFeedSetEvent.OutputObject>;
getEvent(key: 'Redeemed'): TypedContractEvent<RedeemedEvent.InputTuple, RedeemedEvent.OutputTuple, RedeemedEvent.OutputObject>;
getEvent(key: 'RewardsPoolClaimed'): TypedContractEvent<RewardsPoolClaimedEvent.InputTuple, RewardsPoolClaimedEvent.OutputTuple, RewardsPoolClaimedEvent.OutputObject>;
getEvent(key: 'StaxSwapPoolSet'): TypedContractEvent<StaxSwapPoolSetEvent.InputTuple, StaxSwapPoolSetEvent.OutputTuple, StaxSwapPoolSetEvent.OutputObject>;
getEvent(key: 'StaxTokenSet'): TypedContractEvent<StaxTokenSetEvent.InputTuple, StaxTokenSetEvent.OutputTuple, StaxTokenSetEvent.OutputObject>;
getEvent(key: 'TickerPoolSet'): TypedContractEvent<TickerPoolSetEvent.InputTuple, TickerPoolSetEvent.OutputTuple, TickerPoolSetEvent.OutputObject>;
getEvent(key: 'TickerPoolV3Set'): TypedContractEvent<TickerPoolV3SetEvent.InputTuple, TickerPoolV3SetEvent.OutputTuple, TickerPoolV3SetEvent.OutputObject>;
getEvent(key: 'TreasuryFeesClaimed'): TypedContractEvent<TreasuryFeesClaimedEvent.InputTuple, TreasuryFeesClaimedEvent.OutputTuple, TreasuryFeesClaimedEvent.OutputObject>;

    filters: {
      
      'BasketCreated(uint256,address,string)': TypedContractEvent<BasketCreatedEvent.InputTuple, BasketCreatedEvent.OutputTuple, BasketCreatedEvent.OutputObject>;
      BasketCreated: TypedContractEvent<BasketCreatedEvent.InputTuple, BasketCreatedEvent.OutputTuple, BasketCreatedEvent.OutputObject>;
    

      'BuyBurnExecuted(uint256,uint256)': TypedContractEvent<BuyBurnExecutedEvent.InputTuple, BuyBurnExecutedEvent.OutputTuple, BuyBurnExecutedEvent.OutputObject>;
      BuyBurnExecuted: TypedContractEvent<BuyBurnExecutedEvent.InputTuple, BuyBurnExecutedEvent.OutputTuple, BuyBurnExecutedEvent.OutputObject>;
    

      'CapsSet(uint256,uint256,uint256)': TypedContractEvent<CapsSetEvent.InputTuple, CapsSetEvent.OutputTuple, CapsSetEvent.OutputObject>;
      CapsSet: TypedContractEvent<CapsSetEvent.InputTuple, CapsSetEvent.OutputTuple, CapsSetEvent.OutputObject>;
    

      'FeeAccrued(uint256,uint256)': TypedContractEvent<FeeAccruedEvent.InputTuple, FeeAccruedEvent.OutputTuple, FeeAccruedEvent.OutputObject>;
      FeeAccrued: TypedContractEvent<FeeAccruedEvent.InputTuple, FeeAccruedEvent.OutputTuple, FeeAccruedEvent.OutputObject>;
    

      'FeeSplit(uint256,uint256,uint256)': TypedContractEvent<FeeSplitEvent.InputTuple, FeeSplitEvent.OutputTuple, FeeSplitEvent.OutputObject>;
      FeeSplit: TypedContractEvent<FeeSplitEvent.InputTuple, FeeSplitEvent.OutputTuple, FeeSplitEvent.OutputObject>;
    

      'HookAllowlistUpdated(address,bool)': TypedContractEvent<HookAllowlistUpdatedEvent.InputTuple, HookAllowlistUpdatedEvent.OutputTuple, HookAllowlistUpdatedEvent.OutputObject>;
      HookAllowlistUpdated: TypedContractEvent<HookAllowlistUpdatedEvent.InputTuple, HookAllowlistUpdatedEvent.OutputTuple, HookAllowlistUpdatedEvent.OutputObject>;
    

      'MintPausedSet(uint256,bool)': TypedContractEvent<MintPausedSetEvent.InputTuple, MintPausedSetEvent.OutputTuple, MintPausedSetEvent.OutputObject>;
      MintPausedSet: TypedContractEvent<MintPausedSetEvent.InputTuple, MintPausedSetEvent.OutputTuple, MintPausedSetEvent.OutputObject>;
    

      'Minted(uint256,address,uint256,uint256,uint256)': TypedContractEvent<MintedEvent.InputTuple, MintedEvent.OutputTuple, MintedEvent.OutputObject>;
      Minted: TypedContractEvent<MintedEvent.InputTuple, MintedEvent.OutputTuple, MintedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PriceFeedSet(address,address,uint48)': TypedContractEvent<PriceFeedSetEvent.InputTuple, PriceFeedSetEvent.OutputTuple, PriceFeedSetEvent.OutputObject>;
      PriceFeedSet: TypedContractEvent<PriceFeedSetEvent.InputTuple, PriceFeedSetEvent.OutputTuple, PriceFeedSetEvent.OutputObject>;
    

      'Redeemed(uint256,address,uint256,uint256,uint256)': TypedContractEvent<RedeemedEvent.InputTuple, RedeemedEvent.OutputTuple, RedeemedEvent.OutputObject>;
      Redeemed: TypedContractEvent<RedeemedEvent.InputTuple, RedeemedEvent.OutputTuple, RedeemedEvent.OutputObject>;
    

      'RewardsPoolClaimed(uint256)': TypedContractEvent<RewardsPoolClaimedEvent.InputTuple, RewardsPoolClaimedEvent.OutputTuple, RewardsPoolClaimedEvent.OutputObject>;
      RewardsPoolClaimed: TypedContractEvent<RewardsPoolClaimedEvent.InputTuple, RewardsPoolClaimedEvent.OutputTuple, RewardsPoolClaimedEvent.OutputObject>;
    

      'StaxSwapPoolSet(address,address,uint24,int24,address)': TypedContractEvent<StaxSwapPoolSetEvent.InputTuple, StaxSwapPoolSetEvent.OutputTuple, StaxSwapPoolSetEvent.OutputObject>;
      StaxSwapPoolSet: TypedContractEvent<StaxSwapPoolSetEvent.InputTuple, StaxSwapPoolSetEvent.OutputTuple, StaxSwapPoolSetEvent.OutputObject>;
    

      'StaxTokenSet(address)': TypedContractEvent<StaxTokenSetEvent.InputTuple, StaxTokenSetEvent.OutputTuple, StaxTokenSetEvent.OutputObject>;
      StaxTokenSet: TypedContractEvent<StaxTokenSetEvent.InputTuple, StaxTokenSetEvent.OutputTuple, StaxTokenSetEvent.OutputObject>;
    

      'TickerPoolSet(address,address,address,uint24,int24,address)': TypedContractEvent<TickerPoolSetEvent.InputTuple, TickerPoolSetEvent.OutputTuple, TickerPoolSetEvent.OutputObject>;
      TickerPoolSet: TypedContractEvent<TickerPoolSetEvent.InputTuple, TickerPoolSetEvent.OutputTuple, TickerPoolSetEvent.OutputObject>;
    

      'TickerPoolV3Set(address,uint24)': TypedContractEvent<TickerPoolV3SetEvent.InputTuple, TickerPoolV3SetEvent.OutputTuple, TickerPoolV3SetEvent.OutputObject>;
      TickerPoolV3Set: TypedContractEvent<TickerPoolV3SetEvent.InputTuple, TickerPoolV3SetEvent.OutputTuple, TickerPoolV3SetEvent.OutputObject>;
    

      'TreasuryFeesClaimed(uint256)': TypedContractEvent<TreasuryFeesClaimedEvent.InputTuple, TreasuryFeesClaimedEvent.OutputTuple, TreasuryFeesClaimedEvent.OutputObject>;
      TreasuryFeesClaimed: TypedContractEvent<TreasuryFeesClaimedEvent.InputTuple, TreasuryFeesClaimedEvent.OutputTuple, TreasuryFeesClaimedEvent.OutputObject>;
    
    };
  }