/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMockPermit2ForRouter } from './IMockPermit2ForRouter.js';
export type { MockUniversalRouter } from './MockUniversalRouter.js';