/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface MockUniversalRouterInterface extends Interface {
    getFunction(nameOrSignature: "execute" | "permit2" | "rates" | "setRate" | "weth"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'execute', values: [BytesLike, BytesLike[], BigNumberish]): string;
encodeFunctionData(functionFragment: 'permit2', values?: undefined): string;
encodeFunctionData(functionFragment: 'rates', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setRate', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'weth', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'execute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'permit2', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rates', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'weth', data: BytesLike): Result;
  }

  

  export interface MockUniversalRouter extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockUniversalRouter;
    waitForDeployment(): Promise<this>;

    interface: MockUniversalRouterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    execute: TypedContractMethod<
      [commands: BytesLike, inputs: BytesLike[], arg2: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    permit2: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    rates: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    setRate: TypedContractMethod<
      [currencyIn: AddressLike, currencyOut: AddressLike, rate: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    weth: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'execute'): TypedContractMethod<
      [commands: BytesLike, inputs: BytesLike[], arg2: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'permit2'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'rates'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setRate'): TypedContractMethod<
      [currencyIn: AddressLike, currencyOut: AddressLike, rate: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'weth'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }