/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'IPausableToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IPausableToken__factory>
getContractFactory(name: 'IPermit2', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IPermit2__factory>
getContractFactory(name: 'IPriceOracle', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IPriceOracle__factory>
getContractFactory(name: 'IUniversalRouter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IUniversalRouter__factory>
getContractFactory(name: 'StaxBasketToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.StaxBasketToken__factory>
getContractFactory(name: 'StaxVault', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.StaxVault__factory>
getContractFactory(name: 'V4PoolLens', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.V4PoolLens__factory>
getContractFactory(name: 'MockERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockERC20__factory>
getContractFactory(name: 'MockERC20Decimals', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockERC20Decimals__factory>
getContractFactory(name: 'MockFreezableERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockFreezableERC20__factory>
getContractFactory(name: 'MockPermit2', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockPermit2__factory>
getContractFactory(name: 'MockPriceOracle', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockPriceOracle__factory>
getContractFactory(name: 'MockWETH', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockWETH__factory>
getContractFactory(name: 'IMockPermit2ForRouter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IMockPermit2ForRouter__factory>
getContractFactory(name: 'MockUniversalRouter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockUniversalRouter__factory>

  getContractAt(name: 'IPausableToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IPausableToken>
getContractAt(name: 'IPermit2', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IPermit2>
getContractAt(name: 'IPriceOracle', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IPriceOracle>
getContractAt(name: 'IUniversalRouter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IUniversalRouter>
getContractAt(name: 'StaxBasketToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.StaxBasketToken>
getContractAt(name: 'StaxVault', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.StaxVault>
getContractAt(name: 'V4PoolLens', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.V4PoolLens>
getContractAt(name: 'MockERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockERC20>
getContractAt(name: 'MockERC20Decimals', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockERC20Decimals>
getContractAt(name: 'MockFreezableERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockFreezableERC20>
getContractAt(name: 'MockPermit2', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockPermit2>
getContractAt(name: 'MockPriceOracle', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockPriceOracle>
getContractAt(name: 'MockWETH', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockWETH>
getContractAt(name: 'IMockPermit2ForRouter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IMockPermit2ForRouter>
getContractAt(name: 'MockUniversalRouter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockUniversalRouter>

  deployContract(name: 'IPausableToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPausableToken>
deployContract(name: 'IPermit2', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPermit2>
deployContract(name: 'IPriceOracle', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPriceOracle>
deployContract(name: 'IUniversalRouter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniversalRouter>
deployContract(name: 'StaxBasketToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.StaxBasketToken>
deployContract(name: 'StaxVault', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.StaxVault>
deployContract(name: 'V4PoolLens', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.V4PoolLens>
deployContract(name: 'MockERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>
deployContract(name: 'MockERC20Decimals', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20Decimals>
deployContract(name: 'MockFreezableERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockFreezableERC20>
deployContract(name: 'MockPermit2', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockPermit2>
deployContract(name: 'MockPriceOracle', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockPriceOracle>
deployContract(name: 'MockWETH', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockWETH>
deployContract(name: 'IMockPermit2ForRouter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IMockPermit2ForRouter>
deployContract(name: 'MockUniversalRouter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUniversalRouter>

  deployContract(name: 'IPausableToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPausableToken>
deployContract(name: 'IPermit2', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPermit2>
deployContract(name: 'IPriceOracle', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPriceOracle>
deployContract(name: 'IUniversalRouter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniversalRouter>
deployContract(name: 'StaxBasketToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.StaxBasketToken>
deployContract(name: 'StaxVault', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.StaxVault>
deployContract(name: 'V4PoolLens', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.V4PoolLens>
deployContract(name: 'MockERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>
deployContract(name: 'MockERC20Decimals', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20Decimals>
deployContract(name: 'MockFreezableERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockFreezableERC20>
deployContract(name: 'MockPermit2', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockPermit2>
deployContract(name: 'MockPriceOracle', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockPriceOracle>
deployContract(name: 'MockWETH', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockWETH>
deployContract(name: 'IMockPermit2ForRouter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IMockPermit2ForRouter>
deployContract(name: 'MockUniversalRouter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUniversalRouter>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  