/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface V4PoolLensInterface extends Interface {
    getFunction(nameOrSignature: "getLiquidity" | "getLiquidityBatch" | "poolManager"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getLiquidity', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getLiquidityBatch', values: [BytesLike[]]): string;
encodeFunctionData(functionFragment: 'poolManager', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'getLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLiquidityBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'poolManager', data: BytesLike): Result;
  }

  

  export interface V4PoolLens extends BaseContract {
    
    connect(runner?: ContractRunner | null): V4PoolLens;
    waitForDeployment(): Promise<this>;

    interface: V4PoolLensInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getLiquidity: TypedContractMethod<
      [poolId: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    getLiquidityBatch: TypedContractMethod<
      [poolIds: BytesLike[], ],
      [bigint[]],
      'view'
    >
    

    
    poolManager: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getLiquidity'): TypedContractMethod<
      [poolId: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getLiquidityBatch'): TypedContractMethod<
      [poolIds: BytesLike[], ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'poolManager'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }