/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IPausableToken, IPausableTokenInterface } from "../../StaxVault.sol/IPausableToken.js";

  const _abi = [
  {
    "inputs": [],
    "name": "oraclePaused",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IPausableToken__factory {
    static readonly abi = _abi;
    static createInterface(): IPausableTokenInterface {
      return new Interface(_abi) as IPausableTokenInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IPausableToken {
      return new Contract(address, _abi, runner) as unknown as IPausableToken;
    }
  }
  