/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockUniversalRouterSol from './MockUniversalRouter.sol/index.js';
export type { mockUniversalRouterSol };
export type { MockERC20 } from './MockERC20.js';
export type { MockERC20Decimals } from './MockERC20Decimals.js';
export type { MockFreezableERC20 } from './MockFreezableERC20.js';
export type { MockPermit2 } from './MockPermit2.js';
export type { MockPriceOracle } from './MockPriceOracle.js';
export type { MockWETH } from './MockWETH.js';