/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface MockPriceOracleInterface extends Interface {
    getFunction(nameOrSignature: "decimals" | "getRoundData" | "latestRoundData" | "setPrice" | "setPriceAt"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'decimals', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRoundData', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'latestRoundData', values?: undefined): string;
encodeFunctionData(functionFragment: 'setPrice', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setPriceAt', values: [BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'decimals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoundData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'latestRoundData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPriceAt', data: BytesLike): Result;
  }

  

  export interface MockPriceOracle extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockPriceOracle;
    waitForDeployment(): Promise<this>;

    interface: MockPriceOracleInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    decimals: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getRoundData: TypedContractMethod<
      [_roundId: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint] & {roundId: bigint, answer: bigint, startedAt: bigint, updatedAt: bigint, answeredInRound: bigint }],
      'view'
    >
    

    
    latestRoundData: TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, bigint] & {roundId: bigint, answer: bigint, startedAt: bigint, updatedAt: bigint, answeredInRound: bigint }],
      'view'
    >
    

    
    setPrice: TypedContractMethod<
      [newPrice: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setPriceAt: TypedContractMethod<
      [newPrice: BigNumberish, updatedAt_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'decimals'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRoundData'): TypedContractMethod<
      [_roundId: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint] & {roundId: bigint, answer: bigint, startedAt: bigint, updatedAt: bigint, answeredInRound: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'latestRoundData'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, bigint] & {roundId: bigint, answer: bigint, startedAt: bigint, updatedAt: bigint, answeredInRound: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'setPrice'): TypedContractMethod<
      [newPrice: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPriceAt'): TypedContractMethod<
      [newPrice: BigNumberish, updatedAt_: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }