/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as staxVaultSol from './StaxVault.sol/index.js';
export * as mocks from './mocks/index.js';
export { V4PoolLens__factory } from './V4PoolLens__factory.js';