/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IMockPermit2ForRouter, IMockPermit2ForRouterInterface } from "../../../mocks/MockUniversalRouter.sol/IMockPermit2ForRouter.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "from",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "uint160",
        "name": "amount",
        "type": "uint160"
      },
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      }
    ],
    "name": "transferFrom",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IMockPermit2ForRouter__factory {
    static readonly abi = _abi;
    static createInterface(): IMockPermit2ForRouterInterface {
      return new Interface(_abi) as IMockPermit2ForRouterInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IMockPermit2ForRouter {
      return new Contract(address, _abi, runner) as unknown as IMockPermit2ForRouter;
    }
  }
  