/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMockPermit2ForRouter__factory } from './IMockPermit2ForRouter__factory.js';
export { MockUniversalRouter__factory } from './MockUniversalRouter__factory.js';